(function(){
'use strict';
const USD=new Intl.NumberFormat('en-US',{style:'currency',currency:'USD'}),DF=new Intl.DateTimeFormat('en-US',{month:'long',day:'numeric',year:'numeric'});
let state=null,installed=false,observer=null,doc='',path='',day='',busy=false;
const esc=v=>String(v??'').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;'),num=v=>Number.isFinite(Number(v))?Number(v):0,pct=v=>Math.max(0,Math.min(100,num(v))),money=v=>USD.format(num(v));
const localDay=()=>{const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`};
function capture(){const S=window.PTStore;if(!S||S.__clientUpdates)return!!S;S.__clientUpdates=true;for(const name of ['defaultAppState','loadState','saveState']){if(typeof S[name]!=='function')continue;const original=S[name];if(name==='saveState'){S[name]=function(...args){state=args[0]||state;return original.apply(this,args)};continue}S[name]=function(...args){const out=original.apply(this,args);if(out?.then)return out.then(v=>(state=v,v));state=out;return out}}return true}
const project=()=>state?(state.projects||[]).find(p=>p.id===state.activeProjectId)||null:null,folder=()=>String(project()?.folderPath||'').trim(),scan=p=>(window.PTEstimates?.lastScan?.projects||[]).find(x=>x.folder_path===p);
function api(){const E=window.PTEstimates;if(!E||installed)return!!E;installed=true;E.saveClientUpdate=async(p,html,date)=>{const r=await fetch('/api/client-update/save',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({path:p,html,date})}),d=await r.json().catch(()=>({}));if(!r.ok||!d.ok)throw new Error(d.error||r.statusText);return d};return true}
function styles(){if(document.getElementById('clientUpdateStyles'))return;const s=document.createElement('style');s.id='clientUpdateStyles';s.textContent=`#generateClientUpdateButton{margin-left:8px;padding:7px 12px;border:1px solid #2563eb;border-radius:7px;background:#2563eb;color:#fff;font-weight:800}#generateClientUpdateButton:disabled{opacity:.4}.cu-warn{margin-left:6px;padding:2px 7px;border-radius:999px;background:#facc15;color:#713f12;font-size:9px;font-weight:900}#cuModal{position:fixed;inset:0;display:none;z-index:9999;background:#020617b8;padding:24px}#cuModal.open{display:flex;align-items:center;justify-content:center}.cu-shell{width:min(1080px,96vw);height:min(860px,94vh);display:flex;flex-direction:column;background:var(--bg-panel);border:1px solid var(--border);border-radius:12px;overflow:hidden}.cu-bar{display:flex;justify-content:space-between;align-items:center;gap:10px;padding:10px;border-bottom:1px solid var(--border)}.cu-actions{display:flex;gap:6px;flex-wrap:wrap}.cu-path{font-size:10px;color:var(--text-dim);max-width:460px;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}#cuFrame{flex:1;width:100%;border:0;background:#fff}`;document.head.appendChild(s)}
function ui(){const bar=document.getElementById('tabBar');if(!bar)return false;if(!document.getElementById('generateClientUpdateButton')){const b=document.createElement('button');b.id='generateClientUpdateButton';b.type='button';b.textContent='Generate Client Update';b.disabled=true;b.onclick=generate;const a=bar.querySelector('[data-tab="daily-logs"]')||bar.lastElementChild;a?.after(b)}if(!document.getElementById('cuModal')){const m=document.createElement('div');m.id='cuModal';m.innerHTML=`<section class="cu-shell"><header class="cu-bar"><div><strong>Client Update Preview</strong><div id="cuPath" class="cu-path"></div></div><div class="cu-actions"><button id="cuCopy">Copy Rich Text</button><button id="cuPrint">Print / Save PDF</button><button id="cuSave">Save HTML Again</button><button id="cuClose">×</button></div></header><iframe id="cuFrame"></iframe></section>`;document.body.appendChild(m);m.onclick=e=>{if(e.target===m)close()};m.querySelector('#cuClose').onclick=close;m.querySelector('#cuCopy').onclick=copyRich;m.querySelector('#cuPrint').onclick=printDoc;m.querySelector('#cuSave').onclick=saveAgain}return true}
function button(){const b=document.getElementById('generateClientUpdateButton');if(b)b.disabled=!folder()||busy}
const stamp=v=>{const n=Date.parse(String(v||''));return Number.isFinite(n)?n:0};
function data(r){const j=r.job||{},progress=pct(r.daily_log_summary?.percentComplete??j.percentComplete),total=num(j.runningTotal||j.actualTotal||j.estimatedTotal),last=stamp(j.lastClientUpdate);return{j,progress,total,remaining:Math.max(0,total*(1-progress/100)),logs:[...(r.daily_logs||[])].sort((a,b)=>`${b.date}|${b.created}`.localeCompare(`${a.date}|${a.created}`)).slice(0,3),cos:(r.change_orders||[]).filter(x=>x.status==='Approved'&&(!last||stamp(x.approvedAt||x.updated||x.date)>last)).sort((a,b)=>stamp(b.approvedAt||b.updated||b.date)-stamp(a.approvedAt||a.updated||a.date)),date:localDay()}}
const paras=t=>String(t||'').trim()?String(t).split(/\n+/).map(x=>`<p style="margin:0 0 7px">${esc(x)}</p>`).join(''):'<p style="color:#64748b">No details recorded.</p>';
function html(d){const j=d.j,logs=d.logs.length?d.logs.map(l=>`<div style="border:1px solid #e2e8f0;border-radius:9px;padding:13px;margin-top:9px"><div style="display:flex;justify-content:space-between"><div><b>${DF.format(new Date(`${l.date}T12:00:00`))}</b><div style="font-size:12px;color:#64748b">${esc(l.weather||'Weather not recorded')} · ${num(l.crewCount)} crew · ${num(l.hours)} hours each</div></div><b style="font-size:20px;color:#1d4ed8">${pct(l.percentComplete).toFixed(1)}%</b></div><div style="margin-top:9px;line-height:1.5">${paras(l.workPerformed)}</div></div>`).join(''):'<p style="color:#64748b">No daily logs have been entered yet.</p>',cos=d.cos.length?`<table style="width:100%;border-collapse:collapse"><tr><th align="left">Approved change</th><th align="left">Date</th><th align="right">Impact</th></tr>${d.cos.map(c=>`<tr><td style="padding:8px 0;border-top:1px solid #e2e8f0">${esc(c.description)}</td><td style="border-top:1px solid #e2e8f0">${esc(c.date||(c.approvedAt||'').slice(0,10))}</td><td align="right" style="border-top:1px solid #e2e8f0;font-weight:700">${money(c.totalImpact)}</td></tr>`).join('')}</table>`:'<p style="color:#64748b">No newly approved change orders since the previous client update.</p>';
return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${esc(j.name||'Job')} — Client Update</title></head><body style="margin:0;background:#f1f5f9;color:#0f172a;font-family:Arial,sans-serif"><main style="max-width:820px;margin:auto;padding:28px 18px"><section style="background:#fff;border:1px solid #dbe3ec;border-radius:14px;overflow:hidden"><header style="padding:24px 26px;background:#0f2742;color:#fff"><div style="font-size:12px;letter-spacing:.12em;color:#bfdbfe;font-weight:700">WL PAINTING INC. · CLIENT PROGRESS UPDATE</div><h1 style="margin:8px 0 5px">${esc(j.name||'Project')}</h1><div style="color:#dbeafe">${esc(j.address||'Project address not entered')}</div><div style="display:inline-block;margin-top:13px;padding:5px 10px;border-radius:999px;background:#2563eb;font-size:12px;font-weight:700">Status: ${esc(j.status||'—')}</div></header><div style="padding:24px 26px"><p>Current project update as of <b>${DF.format(new Date(`${d.date}T12:00:00`))}</b>.</p><div style="display:grid;grid-template-columns:repeat(3,1fr);gap:10px;margin:18px 0 24px"><div style="border:1px solid #dbe3ec;border-radius:9px;padding:12px"><small>COMPLETE</small><div style="font-size:23px;font-weight:800">${d.progress.toFixed(1)}%</div></div><div style="border:1px solid #dbe3ec;border-radius:9px;padding:12px"><small>CURRENT CONTRACT</small><div style="font-size:19px;font-weight:800">${money(d.total)}</div></div><div style="border:1px solid #dbe3ec;border-radius:9px;padding:12px"><small>REMAINING ESTIMATED</small><div style="font-size:19px;font-weight:800">${money(d.remaining)}</div></div></div><h2 style="border-bottom:2px solid #1d4ed8;padding-bottom:6px">Recent Work and Progress</h2>${logs}<h2 style="margin-top:25px;border-bottom:2px solid #1d4ed8;padding-bottom:6px">Approved Changes Since Last Update</h2>${cos}<p style="margin-top:25px;padding-top:15px;border-top:1px solid #dbe3ec;color:#475569">Please contact WL Painting Inc. with any questions regarding scheduling, access, or coordination.</p></div></section></main></body></html>`}
async function generate(){const p=folder();if(!p||busy)return;busy=true;button();const b=document.getElementById('generateClientUpdateButton'),old=b.textContent;b.textContent='Generating…';try{const r=await window.PTEstimates.getProject(p),d=data(r);doc=html(d);path=p;day=d.date;const saved=await window.PTEstimates.saveClientUpdate(p,doc,day),s=scan(p);if(s){s.job=saved.job;s.client_update_summary=saved.summary}show(saved.file);decorate();window.dispatchEvent(new CustomEvent('pt:client-update-generated',{detail:{path:p,file:saved.file}}))}catch(e){alert(`Could not generate client update: ${e.message||e}`)}finally{busy=false;b.textContent=old;button()}}
function show(file){document.getElementById('cuFrame').srcdoc=doc;document.getElementById('cuPath').textContent=file?`Saved: ${file}`:'';document.getElementById('cuModal').classList.add('open')}
function close(){document.getElementById('cuModal')?.classList.remove('open')}
async function copyRich(){const p=new DOMParser().parseFromString(doc,'text/html'),rich=p.body.innerHTML,plain=p.body.innerText;try{if(navigator.clipboard?.write&&window.ClipboardItem)await navigator.clipboard.write([new ClipboardItem({'text/html':new Blob([rich],{type:'text/html'}),'text/plain':new Blob([plain],{type:'text/plain'})})]);else{const h=document.createElement('div');h.contentEditable='true';h.style.position='fixed';h.style.left='-10000px';h.innerHTML=rich;document.body.appendChild(h);const r=document.createRange();r.selectNodeContents(h);const s=getSelection();s.removeAllRanges();s.addRange(r);document.execCommand('copy');h.remove()}alert('Client update copied as rich text.')}catch(e){alert(`Copy failed: ${e.message||e}`)}}
function printDoc(){let f=document.getElementById('cuPrintFrame');if(!f){f=document.createElement('iframe');f.id='cuPrintFrame';f.style='position:fixed;width:1px;height:1px;right:0;bottom:0;border:0';document.body.appendChild(f)}f.onload=()=>{f.contentWindow?.focus();f.contentWindow?.print()};f.srcdoc=doc}
async function saveAgain(){try{const saved=await window.PTEstimates.saveClientUpdate(path,doc,day),s=scan(path);if(s){s.job=saved.job;s.client_update_summary=saved.summary}document.getElementById('cuPath').textContent=`Saved: ${saved.file}`;decorate();alert('Client update HTML saved.')}catch(e){alert(`Save failed: ${e.message||e}`)}}
function decorate(){const list=window.PTEstimates?.lastScan?.projects||[];document.querySelectorAll('#commandCenterBoard .cc-card').forEach(c=>{const p=list.find(x=>x.folder_path===c.dataset.path),i=p?.client_update_summary||p?.job||{},t=c.querySelector('.cc-card-name');t?.querySelector('.cu-warn')?.remove();if(i.clientUpdateOverdue&&t)t.insertAdjacentHTML('beforeend',`<span class="cu-warn" title="No client update for ${num(i.daysSinceClientUpdate)} days">Update ${num(i.daysSinceClientUpdate)}d overdue</span>`)})}
function watch(){const b=document.getElementById('commandCenterBoard');if(!b||observer)return!!b;observer=new MutationObserver(decorate);observer.observe(b,{childList:true,subtree:true});decorate();return true}
function all(){capture();api();styles();ui();watch();button()}
window.PTClientUpdates={generate,copy:copyRich,print:printDoc};capture();document.addEventListener('DOMContentLoaded',()=>{all();let n=0;const timer=setInterval(()=>{all();decorate();if(++n>300&&!project())clearInterval(timer)},500)});window.addEventListener('pt:jobs-scan',()=>setTimeout(decorate,0));
})();
